version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "17:00"
      timezone: America/New_York
    open-pull-requests-limit: 10
    commit-message:
      prefix: "ci"
      include: scope
    reviewers:
      - davidlday
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      timezone: America/New_York
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix"
      prefix-development: "build"
      include: scope
    reviewers:
      - davidlday
    groups:
      dev-typescript-eslint:
        dependency-type: "development"
        patterns:
          - "@typescript-eslint/*"
      dev-mocha:
        dependency-type: "development"
        patterns:
          - "mocha"
          - "@types/mocha"
