env:
  node: true
  es2021: true
  mocha: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - "@typescript-eslint"
ignorePatterns:
  - "node_modules"
  - "out"
  - "**/*.json"
rules:
  "@typescript-eslint/no-unused-vars":
    - warn
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
