name: Bump Version and Create Release

on:
  schedule:
    - cron: "0 17 * * 5" # Every Friday at 17:00 UTC (noon EST / 1pm EDT)
  workflow_dispatch:

concurrency:
  group: tag-and-release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu-build:
    uses: ./.github/workflows/build-ubuntu.yml

  macos-build:
    uses: ./.github/workflows/build-macos.yml

  windows-build:
    uses: ./.github/workflows/build-windows.yml

  bump-and-release:
    needs:
      - ubuntu-build
      - macos-build
      - windows-build
    # if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true
          token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@0.27.1
        with:
          commit: true
          push: true
          github_token: ${{ secrets.VERSION_BUMP_TAG_TOKEN }}
          changelog_increment_filename: "release-body.md"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          body_path: "release-body.md"
          tag_name: v${{ steps.cz.outputs.version }}
