name: Publish Extension to Marketplaces

on:
  push:
    tags:
      - "v*"

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish-openvsx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: lts/*
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPENVSX_PERSONAL_ACCESS_TOKEN }}
  publish-vscode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version: lts/*
      - run: npm ci
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VSCODE_PERSONAL_ACCESS_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com
