name: VSCE Publish

on:
  push:
    tags:
      - "v*"

concurrency:
  group: publish-openvsx-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.3
        with:
          node-version: lts/*
      - run: npm ci
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v1
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPENVSX_PERSONAL_ACCESS_TOKEN }}
#  Original job
# jobs:
#   publish:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v4
#     - uses: actions/setup-node@v1
#       with:
#         node-version: 14
#     - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
#       name: Start Xvfb
#     - run: npm install -g typescript vsce
#     - run: npm ci
#     - run: vsce package
#     - run: vsce publish --pat ${{ secrets.VSCODE_PERSONAL_ACCESS_TOKEN }}
